component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/chatserver/.*
- ./bin/chatserver/client/.*
- ./bin/cmdserver/.*
- ./bin/dateserver/.*
- ./bin/echoserver/.*
- ./bin/echowebserver/.*
- ./bin/filesrv/.*
- ./bin/ftpserver/.*
- ./bin/icons/.*
- ./bin/org/.*
- ./bin/org/quickserver/.*
- ./bin/org/quickserver/net/.*
- ./bin/org/quickserver/net/client/.*
- ./bin/org/quickserver/net/qsadmin/.*
- ./bin/org/quickserver/net/qsadmin/gui/.*
- ./bin/org/quickserver/net/qsadmin/gui/conf/.*
- ./bin/org/quickserver/net/server/.*
- ./bin/org/quickserver/net/server/gui/.*
- ./bin/org/quickserver/net/server/impl/.*
- ./bin/org/quickserver/security/.*
- ./bin/org/quickserver/sql/.*
- ./bin/org/quickserver/swing/.*
- ./bin/org/quickserver/util/.*
- ./bin/org/quickserver/util/io/.*
- ./bin/org/quickserver/util/logging/.*
- ./bin/org/quickserver/util/pool/.*
- ./bin/org/quickserver/util/pool/thread/.*
- ./bin/org/quickserver/util/xmlreader/.*
- ./bin/pipeserver/.*
- ./bin/test/.*
- ./bin/test/org/.*
- ./bin/test/org/quickserver/.*
- ./bin/test/org/quickserver/net/.*
- ./bin/test/org/quickserver/net/server/.*
- ./bin/xmladder/.*
- ./dist/.*
- ./docs/.*
- ./docs/index-files/.*
- ./docs/org/.*
- ./docs/org/quickserver/.*
- ./docs/org/quickserver/net/.*
- ./docs/org/quickserver/net/class-use/.*
- ./docs/org/quickserver/net/qsadmin/.*
- ./docs/org/quickserver/net/qsadmin/class-use/.*
- ./docs/org/quickserver/net/qsadmin/gui/.*
- ./docs/org/quickserver/net/qsadmin/gui/class-use/.*
- ./docs/org/quickserver/net/server/.*
- ./docs/org/quickserver/net/server/class-use/.*
- ./docs/org/quickserver/net/server/impl/.*
- ./docs/org/quickserver/net/server/impl/class-use/.*
- ./docs/org/quickserver/security/.*
- ./docs/org/quickserver/security/class-use/.*
- ./docs/org/quickserver/sql/.*
- ./docs/org/quickserver/sql/class-use/.*
- ./docs/org/quickserver/swing/.*
- ./docs/org/quickserver/swing/class-use/.*
- ./docs/org/quickserver/util/.*
- ./docs/org/quickserver/util/io/.*
- ./docs/org/quickserver/util/io/class-use/.*
- ./docs/org/quickserver/util/logging/.*
- ./docs/org/quickserver/util/logging/class-use/.*
- ./docs/org/quickserver/util/pool/.*
- ./docs/org/quickserver/util/pool/class-use/.*
- ./docs/org/quickserver/util/pool/thread/.*
- ./docs/org/quickserver/util/pool/thread/class-use/.*
- ./docs/org/quickserver/util/xmlreader/.*
- ./docs/org/quickserver/util/xmlreader/class-use/.*
- ./etc/.*
- ./examples/.*
- ./examples/conf/.*
- ./examples/db/.*
- ./examples/dist/.*
- ./examples/log/.*
- ./examples/win_nt_services/.*
